import { ICondition } from "../condition";
export * from "./isPlayersTurn";
export * from "./matchesRank";
export * from "./matchesSuit";
export * from "./targetsNameIs";
export * from "./isOwner";
export * from "./isSelected";
export * from "./hasAtLeastXEntitiesSelected";
export * from "./matchesSelectedWith";
export { default as selectedEntities } from "./selectedEntities";
export declare const OR: (...conditions: ICondition[]) => ICondition;
export declare const AND: (...conditions: ICondition[]) => ICondition;
export declare const NOT: (...conditions: ICondition[]) => ICondition;
