# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/node:20.9.0

jobs:
  install:
    executor: my-executor
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore cache for all dependencies
          keys:
            - v6-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v6-dependencies-

      # bootstraps right after installation
      - run: npm ci

      - save_cache:
          name: Save cache for all dependencies
          key: v6-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - packages/*/node_modules
            - examples/*/node_modules

  build-core:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build whole core
          command: NODE_ENV=production npm run build:ci

      - persist_to_workspace:
          root: ~/project
          paths:
            - packages/*/lib
            - examples/*/dist

  build-examples:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build examples
          command: NODE_ENV=production npm run build -- "example*"

  test:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Test with coverage (leave cover results for later)
          command: npm run test:ci

      - persist_to_workspace:
          root: ~/project
          paths:
            - coverage

  lint:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Linting
          command: npm run lint

  release-and-publish:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Release & Publish
          command: |
            git config --global user.email ${GIT_AUTHOR_EMAIL}
            git config --global user.name ${GIT_AUTHOR_NAME}
            npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
            npm run release:ci -- --yes

  documentation-deploy:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project

      - run:
          name: Prepare env vars
          command: |
            if [[ "$CIRCLE_BRANCH" == "development" ]]; then
              SubDomain="dev-"
            elif [[ "$CIRCLE_BRANCH" != "main" ]]; then
              echo "can't deploy docs from $CIRCLE_BRANCH branch. This step shouldn't execute anyway!"
              exit 1
            fi
            S3_BUCKET="s3://${SubDomain}cardsgame.darekgreenly.com"
            echo "S3_BUCKET = $S3_BUCKET"
            echo "export S3_BUCKET=$S3_BUCKET" >> $BASH_ENV
            echo "export AWS_REGION=eu-central-1" >> $BASH_ENV

      - run:
          name: Install & build
          working_directory: docs
          command: |
            npm ci
            npm run build

      # whole docs/build directory
      - aws-s3/sync:
          arguments: --delete --cache-control "public, max-age=31536000, immutable"
          aws-region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: "docs/build"
          to: "${S3_BUCKET}"

      # index and sitemap with clear cache thing
      - aws-s3/copy:
          arguments: --cache-control "max-age=604800, no-cache"
          from: "docs/build/index.html"
          to: "${S3_BUCKET}/index.html"
      - aws-s3/copy:
          arguments: --cache-control "max-age=604800, no-cache"
          from: "docs/build/sitemap.xml"
          to: "${S3_BUCKET}/sitemap.xml"

      - when:
          condition:
            equal: [<< pipeline.git.branch >>, "development"]
          steps:
            - aws-s3/copy:
                arguments: --cache-control "public, max-age=31536000, immutable"
                from: "docs/dev.robots.txt"
                to: "${S3_BUCKET}/robots.txt"

  coverage:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project

      - run:
          name: Send coverage report to Coveralls
          command: npm run coveralls

  sonarcloud:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project

      - sonarcloud/scan

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

anchors-filters:
  - &filters-main-and-development
    filters:
      branches:
        only:
          - development
          - main
  - &filters-only-main
    filters:
      branches:
        only: main

workflows:
  version: 2

  ci:
    jobs:
      - install

      - lint:
          requires:
            - install
      - build-core:
          requires:
            - install
      - build-examples:
          requires:
            - build-core

      - test:
          requires:
            - build-core

      - release-and-publish:
          <<: *filters-only-main
          requires:
            - lint
            - test
      - documentation-deploy:
          <<: *filters-main-and-development
          requires:
            - lint
            - test

      - sonarcloud:
          <<: *filters-main-and-development
          context: SonarCloud
          requires:
            - test
      - coverage:
          <<: *filters-main-and-development
          requires:
            - test
