# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  prepare:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci
      - run: npm run bootstrap
      - run: npm run build:utils

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            # - node_modules
            - /root/.npm

  test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/repo

    steps:
      # run tests!
      - run: npm test

workflows:
  version: 2
  test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
